import Link from "next/link";
import { getTripDiscovery } from "@/server/projections/trips";
import { formatTripDateTime } from "@/features/trips/format";

export default async function ExplorePage(){
 const projection=await getTripDiscovery();
 if(projection.status==="UNAUTHENTICATED")return <main className="min-h-screen bg-zinc-100 px-5 py-10"><div className="mx-auto max-w-xl rounded-3xl bg-white p-8 shadow-sm"><p className="text-sm font-medium text-zinc-500">Explore</p><h1 className="mt-2 text-3xl font-semibold">Sign in to see where you could go</h1><Link href="/auth/sign-in?next=/explore" className="mt-6 inline-flex rounded-2xl bg-zinc-950 px-5 py-3 text-sm font-semibold text-white">Sign in</Link></div></main>;
 const offerings=projection.status==="READY"?projection.offerings:[];
 return <main className="min-h-screen bg-zinc-100 px-5 py-10 text-zinc-950"><div className="mx-auto max-w-4xl"><div className="flex items-center justify-between"><Link href="/" className="text-sm font-semibold text-zinc-600">← Home</Link><Link href="/go" className="text-sm font-semibold text-zinc-600">I know where I need to go</Link></div><p className="mt-8 text-xs font-semibold uppercase tracking-[0.16em] text-emerald-700">Explore · Raahi Trips</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">Where could I go?</h1><p className="mt-3 max-w-2xl text-zinc-600">Discover Driver-created shared day journeys. Raahi Trips sell mobility—transport, destination wait and return—not bundled hotels, guides, meals or tickets.</p>
 <div className="mt-8 grid gap-5 md:grid-cols-2">{offerings.map(t=><Link key={t.offering_id} href={`/explore/${t.offering_id}`} className="overflow-hidden rounded-3xl bg-white shadow-sm transition hover:shadow-md"><div className="flex min-h-36 items-end bg-zinc-900 p-6 text-white"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-zinc-300">From {t.origin_name}</p><h2 className="mt-2 text-3xl font-semibold">{t.destination_name}</h2></div></div><div className="p-6"><div className="flex items-start justify-between gap-4"><div><p className={`text-xs font-semibold uppercase tracking-[0.12em] ${t.display_status==="CONFIRMED"?"text-emerald-700":t.display_status==="FULL"?"text-zinc-500":"text-amber-700"}`}>{t.display_status}</p><p className="mt-2 text-sm text-zinc-700">Go {formatTripDateTime(t.departure_at)}</p><p className="mt-1 text-sm text-zinc-700">Return {formatTripDateTime(t.return_departure_at)}</p></div><div className="text-right"><p className="text-2xl font-semibold">₹{t.price_per_seat_inr}</p><p className="text-xs text-zinc-500">per seat</p></div></div>{t.status==="FILLING"?<p className="mt-4 rounded-2xl bg-amber-50 p-3 text-sm text-amber-950">{t.seats_needed_to_confirm} more seat{t.seats_needed_to_confirm===1?"":"s"} needed to confirm by {formatTripDateTime(t.confirmation_deadline)}.</p>:<p className="mt-4 rounded-2xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-900">Your trip can be booked as confirmed.</p>}<div className="mt-4 flex items-center justify-between text-sm"><span>{t.seats_left} seat{t.seats_left===1?"":"s"} left</span><span className="font-semibold">{t.driver_name} · {t.vehicle_model}</span></div></div></Link>)}{offerings.length===0?<div className="rounded-3xl bg-white p-7 shadow-sm md:col-span-2"><h2 className="text-xl font-semibold">No Raahi Trip is open right now</h2><p className="mt-2 text-sm text-zinc-600">Driver-created day journeys will appear here when they are published.</p></div>:null}</div></div></main>;
}
