export const tripMessages: Record<string, [number, string]> = {
  PASSENGER_CAPABILITY_REQUIRED: [403, "Passenger access is required."],
  DRIVER_CAPABILITY_REQUIRED: [403, "Driver access is required."],
  TRIP_PRODUCT_NOT_AVAILABLE: [409, "Raahi Trips is not available from this origin right now."],
  TRIP_DRIVER_NOT_ELIGIBLE: [409, "Your Driver, Vehicle, or current Operating Market is not eligible for this Trip."],
  TRIP_CAPACITY_INVALID: [422, "Choose a valid number of seats."],
  TRIP_THRESHOLD_INVALID: [422, "Choose a valid minimum confirmation threshold."],
  TRIP_PRICE_INVALID: [422, "Choose a valid per-seat price."],
  TRIP_ORIGIN_INVALID: [422, "Choose an eligible origin."],
  TRIP_DESTINATION_INVALID: [422, "Choose a valid destination."],
  TRIP_DEPARTURE_INVALID: [422, "Choose a valid future departure time."],
  TRIP_RETURN_INVALID: [422, "Return must be after the outbound departure."],
  TRIP_CONFIRMATION_DEADLINE_INVALID: [422, "Choose a valid confirmation deadline before departure."],
  TRIP_COMMITMENT_CONFLICT: [409, "This Driver or Vehicle already has another commitment in that time window."],
  TRIP_OFFERING_NOT_FOUND: [404, "Raahi Trip not found."],
  TRIP_OFFERING_NOT_EDITABLE: [409, "This Trip can no longer be edited."],
  TRIP_ALREADY_BOOKED: [409, "Trip terms are locked after the first Passenger booking."],
  TRIP_OFFERING_NOT_PUBLISHABLE: [409, "This Trip can no longer be published."],
  TRIP_OFFERING_NOT_CANCELLABLE: [409, "This Trip can no longer be cancelled before fulfilment."],
  TRIP_ALREADY_IN_FULFILMENT: [409, "This Trip has already entered fulfilment. Use support for an in-progress exception."],
  TRIP_OFFERING_NOT_BOOKABLE: [409, "This Trip is no longer bookable."],
  TRIP_CONFIRMATION_DEADLINE_PASSED: [409, "The confirmation deadline has passed."],
  TRIP_DRIVER_CANNOT_BOOK_SELF: [409, "A Driver cannot book seats in their own Raahi Trip."],
  TRIP_CAPACITY_UNAVAILABLE: [409, "Those seats are no longer available."],
  TRIP_ACTIVE_BOOKING_EXISTS: [409, "You already have an active booking on this Trip."],
  TRIP_CONFIRMATION_STATE_INVALID: [409, "Trip confirmation state is inconsistent. Refresh and try again."],
  TRIP_BOOKING_NOT_FOUND: [404, "Trip booking not found."],
  TRIP_BOOKING_NOT_CANCELLABLE: [409, "This booking can no longer be cancelled from the booking screen."],
  TRIP_LOCATION_NOT_VERIFIED: [422, "Raahi could not verify this Trip location step."],
  RIDE_TRANSITION_INVALID: [409, "That Trip action is not available in the current state."],
  RIDE_NOT_FOUND: [404, "Ride not found."],
  BOOKING_NOT_FOUND: [404, "Booking not found."],
  BOOKING_TRANSITION_INVALID: [409, "That Passenger action is not available in the current state."],
  BOARDING_WAIT_NOT_EXPIRED: [409, "The boarding wait has not finished yet."],
  RETURN_WAIT_NOT_FINISHED: [409, "The planned return time has not arrived yet."],
  RETURN_BOARDING_WAIT_NOT_EXPIRED: [409, "The return boarding wait has not finished yet."],
  RETURN_MANIFEST_UNRESOLVED: [409, "Resolve every returning Passenger before departure."],
  IDEMPOTENCY_CONFLICT: [409, "This action key was already used with different details."],
};

export function mapTripError(message: string): [string, number, string] | null {
  const hit = Object.entries(tripMessages).find(([code]) => message.includes(code));
  return hit ? [hit[0], hit[1][0], hit[1][1]] : null;
}
