'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { CarFront, Loader2, RefreshCw, ShieldCheck } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '@/contexts/AuthContext';
import { getAdminOutstationMarketplace, type AdminOutstationRow } from '@/lib/outstationApi';

export default function AdminOutstationMarketplace(){
  const {profile}=useAuth(); const [rows,setRows]=useState<AdminOutstationRow[]>([]); const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{if(profile?.role!=='admin')return;setLoading(true);try{setRows(await getAdminOutstationMarketplace());}catch(e:any){toast.error(e.message||'Could not load Outstation marketplace');}finally{setLoading(false);}},[profile?.role]);
  useEffect(()=>{void load();},[load]);
  const stats=useMemo(()=>({open:rows.filter(r=>r.effective_status==='OPEN').length,accepted:rows.filter(r=>r.effective_status==='ACCEPTED').length,quotes:rows.reduce((n,r)=>n+Number(r.quote_count||0),0)}),[rows]);
  if(profile?.role!=='admin')return null;
  return <main className="mx-auto max-w-screen-2xl space-y-5 px-4 py-5 sm:px-6">
    <section className="hero-surface"><p className="text-[11px] font-bold uppercase tracking-[0.14em] text-amber-200">Operations · Outstation</p><h1 className="mt-2 text-2xl font-extrabold text-white sm:text-3xl">Lead & quote marketplace</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-white/75">Observe Passenger requests, Driver response and selected quotes. Fixed-route FIFO remains a separate transport engine.</p></section>
    <div className="grid grid-cols-3 gap-2"><Metric label="Open requests" value={stats.open}/><Metric label="Accepted" value={stats.accepted}/><Metric label="Live quotes" value={stats.quotes}/></div>
    <section className="rounded-2xl border border-green-200 bg-green-50 p-4"><div className="flex gap-3"><ShieldCheck size={18} className="mt-0.5 shrink-0 text-green-700"/><div><p className="text-sm font-extrabold text-green-900">Trust boundary</p><p className="mt-1 text-xs leading-relaxed text-green-800">Only fully verified Drivers can quote. Passenger contact details are visible to the selected Driver only after acceptance; raw Licence/RC documents stay private.</p></div></div></section>
    <section className="space-y-3"><div className="flex items-end justify-between gap-3"><div><p className="section-label">Marketplace activity</p><h2 className="mt-1 text-lg font-extrabold">Requests</h2></div><button onClick={load} className="btn-outline px-3 py-2"><RefreshCw size={14}/>Refresh</button></div>{loading&&<div className="flex justify-center py-10"><Loader2 className="animate-spin text-primary"/></div>}{!loading&&rows.length===0&&<div className="feature-card p-8 text-center text-sm text-muted-foreground">No Outstation activity yet.</div>}{rows.map(row=><div key={row.request_id} className="feature-card p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-extrabold">{row.origin_name} → {row.destination_text}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(row.departure_at).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})} · {row.travel_type==='ROUND_TRIP'?'Round trip':'One way'} · {row.passenger_count} passenger{row.passenger_count===1?'':'s'}</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${row.effective_status==='OPEN'?'bg-blue-50 text-blue-700':row.effective_status==='ACCEPTED'?'bg-green-50 text-green-700':'bg-muted text-muted-foreground'}`}>{row.effective_status}</span></div><div className="mt-3 grid gap-2 sm:grid-cols-3"><Info label="Passenger" value={`${row.passenger_name}${row.passenger_phone?` · ${row.passenger_phone}`:''}`}/><Info label="Quotes" value={String(row.quote_count)}/><Info label="Selected" value={row.accepted_driver_name?`${row.accepted_driver_name} · ₹${row.accepted_price?.toLocaleString('en-IN')}`:'—'}/></div>{row.accepted_vehicle_number&&<p className="mt-3 text-xs text-muted-foreground">Selected vehicle · {row.accepted_vehicle_number}{row.accepted_driver_phone?` · Driver ${row.accepted_driver_phone}`:''}</p>}</div>)}</section>
  </main>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-border bg-card p-3 card-shadow-sm"><p className="text-[10px] font-bold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-xl font-extrabold">{value}</p></div>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-muted/60 px-3 py-2"><p className="text-[10px] font-bold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 truncate text-xs font-bold">{value}</p></div>}
