import Link from "next/link";
import { getCarpoolCatalog, getCarpoolDiscovery } from "@/server/projections/carpool";
import { formatCarpoolDateTime } from "@/features/carpool/format";

export default async function CarpoolPage(){
 const[catalogProjection,discoveryProjection]=await Promise.all([getCarpoolCatalog(),getCarpoolDiscovery()]);
 if(catalogProjection.status==="UNAUTHENTICATED"||discoveryProjection.status==="UNAUTHENTICATED")return <main className="min-h-screen bg-zinc-100 px-5 py-10"><div className="mx-auto max-w-xl rounded-3xl bg-white p-8 shadow-sm"><p className="text-sm font-medium text-zinc-500">Carpool</p><h1 className="mt-2 text-3xl font-semibold">Sign in to find a shared journey</h1><Link href="/auth/sign-in?next=/carpool" className="mt-6 inline-flex rounded-2xl bg-zinc-950 px-5 py-3 text-sm font-semibold text-white">Sign in</Link></div></main>;
 const journeys=discoveryProjection.status==="READY"?discoveryProjection.journeys:[];const catalog=catalogProjection.status==="READY"?catalogProjection.catalog:null;
 return <main className="min-h-screen bg-zinc-100 px-5 py-10 text-zinc-950"><div className="mx-auto max-w-3xl"><Link href="/go" className="text-sm font-semibold text-zinc-600">← Find a ride</Link><p className="mt-8 text-xs font-semibold uppercase tracking-[0.16em] text-zinc-500">Carpool</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">Driver is already going</h1><p className="mt-3 max-w-2xl text-zinc-600">Book spare seats in a Driver’s real personal journey. Eligible seats book instantly—there is no Driver approval queue.</p>{catalog?.products.length===0?<p className="mt-8 rounded-2xl bg-white p-5">Carpool is not active in this market yet.</p>:null}<div className="mt-8 space-y-4">{journeys.map(j=><Link key={j.journey_id} href={`/carpool/${j.journey_id}`} className="block rounded-3xl bg-white p-6 shadow-sm transition hover:shadow-md"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-emerald-700">Driver is already going</p><h2 className="mt-2 text-2xl font-semibold">{j.origin_name} → {j.destination_name}</h2><p className="mt-2 text-sm text-zinc-600">{formatCarpoolDateTime(j.departure_at)} · {j.driver_name}</p><p className="mt-1 text-sm text-zinc-600">{j.vehicle_model} · {j.vehicle_registration}</p></div><div className="text-right"><p className="text-2xl font-semibold">₹{j.contribution_per_seat_inr}</p><p className="text-xs text-zinc-500">per seat</p><p className="mt-2 text-sm font-semibold">{j.seats_left} seat{j.seats_left===1?"":"s"} left</p></div></div><div className="mt-4 flex flex-wrap gap-2 text-xs font-semibold text-emerald-800">{j.trust.driver_verified?<span className="rounded-full bg-emerald-50 px-3 py-1">DL verified</span>:null}{j.trust.vehicle_rc_verified?<span className="rounded-full bg-emerald-50 px-3 py-1">RC verified</span>:null}{j.trust.vehicle_photos_verified?<span className="rounded-full bg-emerald-50 px-3 py-1">Vehicle photos verified</span>:null}</div></Link>)}{journeys.length===0?<div className="rounded-3xl bg-white p-7 shadow-sm"><h2 className="text-xl font-semibold">No published Carpool journey right now</h2><p className="mt-2 text-sm text-zinc-600">When a Driver publishes spare seats for a real journey, it will appear here.</p></div>:null}</div></div></main>;
}
