'use client';
import React, { useState, useEffect, useCallback } from 'react';
import Link from 'next/link';
import { toast } from 'sonner';
import { MapPin, Route, Users, Car, List, Activity, ShieldAlert, ChevronLeft, CheckCircle2, Loader2 } from 'lucide-react';
import { adminGetLocations, adminGetRoutes, adminGetDrivers, adminGetActiveTrips, adminGetBehaviourEvents, adminRestrictUser, adminUnrestrictUser, getDriverQueueStatus } from '@/lib/raahiApi';
import { useAuth } from '@/contexts/AuthContext';
import StatusBadge from '@/components/ui/StatusBadge';
import AppLogo from '@/components/ui/AppLogo';

type AdminTab='locations'|'routes'|'drivers'|'queue'|'trips'|'behaviour';
const TABS=[{id:'locations' as const,label:'Locations',icon:<MapPin size={16}/>},{id:'routes' as const,label:'Routes & Stops',icon:<Route size={16}/>},{id:'drivers' as const,label:'Drivers',icon:<Users size={16}/>},{id:'queue' as const,label:'Driver Queue',icon:<List size={16}/>},{id:'trips' as const,label:'Active Trips',icon:<Car size={16}/>},{id:'behaviour' as const,label:'Behaviour',icon:<Activity size={16}/>}];

export default function AdminPanelContent(){const[activeTab,setActiveTab]=useState<AdminTab>('trips');const{profile,loading}=useAuth();if(loading)return <Loading/>;if(!profile||profile.role!=='admin')return <div className="px-4 py-12 text-center"><ShieldAlert className="mx-auto opacity-40"/><p className="font-semibold mt-3">Admin Access Required</p></div>;return <div className="max-w-screen-2xl mx-auto"><header className="sticky top-0 z-40 bg-card border-b"><div className="flex items-center gap-3 px-4 h-14"><Link href="/"><ChevronLeft/></Link><AppLogo size={28}/><b>Raahi Admin</b></div><div className="flex overflow-x-auto px-2">{TABS.map(t=><button key={t.id} onClick={()=>setActiveTab(t.id)} className={`flex items-center gap-1.5 px-3 py-3 text-xs font-semibold whitespace-nowrap border-b-2 ${activeTab===t.id?'border-primary text-primary':'border-transparent text-muted-foreground'}`}>{t.icon}{t.label}</button>)}</div></header><div className="px-4 py-4">{activeTab==='locations'&&<LocationsTab/>}{activeTab==='routes'&&<RoutesTab/>}{activeTab==='drivers'&&<DriversTab/>}{activeTab==='queue'&&<QueueTab/>}{activeTab==='trips'&&<TripsTab/>}{activeTab==='behaviour'&&<BehaviourTab/>}</div></div>}
const Loading=()=> <div className="flex justify-center py-12"><Loader2 className="animate-spin text-primary"/></div>;
function LocationsTab(){const[x,setX]=useState<any[]>([]);const[l,setL]=useState(true);useEffect(()=>{adminGetLocations().then(d=>{setX(d);setL(false)})},[]);if(l)return <Loading/>;return <div className="space-y-2"><h2 className="font-bold">Locations</h2>{x.map(v=><div className="card p-4 flex justify-between" key={v.id}><span><MapPin size={16} className="inline mr-2"/>{v.name}</span><StatusBadge status={v.is_active?'confirmed':'expired'} label={v.is_active?'Active':'Inactive'}/></div>)}</div>}
function RoutesTab(){const[x,setX]=useState<any[]>([]);const[l,setL]=useState(true);useEffect(()=>{adminGetRoutes().then(d=>{setX(d);setL(false)})},[]);if(l)return <Loading/>;return <div className="space-y-2"><h2 className="font-bold">Routes & Stops</h2>{x.map(r=><div className="card p-4" key={r.id}><b>{r.direction_label}</b><p className="text-xs text-muted-foreground">{r.code} · {(r.route_stops||[]).length} stops</p></div>)}</div>}
function DriversTab(){const[x,setX]=useState<any[]>([]);const[l,setL]=useState(true);const[a,setA]=useState<string|null>(null);const load=useCallback(()=>adminGetDrivers().then(d=>{setX(d);setL(false)}),[]);useEffect(()=>{load()},[load]);if(l)return <Loading/>;return <div className="space-y-2"><div><h2 className="font-bold">Drivers ({x.length})</h2><p className="text-xs text-muted-foreground">Drivers choose a route dynamically for each journey.</p></div>{x.map(d=>{const restricted=d.profiles?.is_restricted??false;return <div className="card p-4 flex justify-between gap-3" key={d.id}><div><b className="text-sm">{d.display_name}</b><p className="text-xs text-muted-foreground">{d.phone}</p><p className="text-xs text-muted-foreground mt-1"><Car size={10} className="inline mr-1"/>{d.vehicles?.registration_number??'No vehicle'} · {d.trips_completed} trips</p></div><button disabled={!!a} onClick={async()=>{setA(d.id);const r=restricted?await adminUnrestrictUser(d.profile_id):await adminRestrictUser(d.profile_id,'Admin restriction');setA(null);if(r.success){toast.success(restricted?'Driver unrestricted':'Driver restricted');load()}else toast.error(r.error||'Failed')}} className={restricted?'text-xs text-green-700':'text-xs text-red-700'}>{a===d.id?<Loader2 size={13} className="animate-spin"/>:restricted?<><CheckCircle2 size={13} className="inline"/> Unrestrict</>:<><ShieldAlert size={13} className="inline"/> Restrict</>}</button></div>})}</div>}
function QueueTab(){const[routes,setRoutes]=useState<any[]>([]);const[id,setId]=useState('');const[q,setQ]=useState<any[]>([]);useEffect(()=>{adminGetRoutes().then(d=>{setRoutes(d);if(d[0])setId(d[0].id)})},[]);useEffect(()=>{if(id)getDriverQueueStatus(id).then(setQ)},[id]);return <div className="space-y-3"><h2 className="font-bold">Driver Queue</h2><div className="flex gap-2 overflow-x-auto">{routes.map(r=><button key={r.id} onClick={()=>setId(r.id)} className={`px-3 py-2 rounded-xl text-xs ${id===r.id?'bg-secondary text-primary':'bg-muted'}`}>{r.code}</button>)}</div>{q.map((e:any)=><div className="card p-4 flex justify-between" key={e.queue_id}><span>#{e.queue_position} {e.driver_name}</span><StatusBadge status={e.status==='ACTIVE_COLLECTING'?'collecting':'held'} label={e.status}/></div>)}</div>}
function TripsTab(){const[x,setX]=useState<any[]>([]);useEffect(()=>{adminGetActiveTrips().then(setX)},[]);return <div className="space-y-2"><h2 className="font-bold">Active Trips</h2>{x.length===0&&<p className="text-sm text-muted-foreground">No active trips.</p>}{x.map(t=><div className="card p-4" key={t.trip_id}><b>{t.route_code}</b><p className="text-xs text-muted-foreground">{t.driver_name} · {t.vehicle_number} · {t.status}</p></div>)}</div>}
function BehaviourTab(){const[x,setX]=useState<any[]>([]);useEffect(()=>{adminGetBehaviourEvents().then(setX)},[]);return <div className="space-y-2"><h2 className="font-bold">Behaviour Events</h2>{x.map((e:any)=><div className="card p-3" key={e.event_id}><p className="text-sm font-semibold">{e.event_type}</p><p className="text-xs text-muted-foreground">{e.actor_role} · {e.actor_name||'Unknown'}</p></div>)}</div>}
