"use client";

import { useRouter } from "next/navigation";
import { useMemo, useState, type FormEvent } from "react";
import { DriverPaymentCard } from "@/features/payment-support/DriverPaymentCard";
import { ReportIssue } from "@/features/payment-support/ReportIssue";
import { formatTripDateTime, tripLocalInputValue } from "./format";
import type { DriverTripOffering, DriverTripWorkspace as Workspace } from "./types";

type ApiResult={ok:boolean;message?:string;value?:{offering_id?:string}};
type FormState={destination:string;departure:string;returnDeparture:string;seats:number;price:number;threshold:number;deadline:string;itinerary:string};
const emptyForm:FormState={destination:"",departure:"",returnDeparture:"",seats:2,price:350,threshold:2,deadline:"",itinerary:""};

export function DriverTripWorkspace({workspace}:{workspace:Workspace}){
 const router=useRouter();const[busy,setBusy]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);const[form,setForm]=useState<FormState>(emptyForm);
 const product=workspace.catalog.products.find(p=>p.market_id===workspace.operating_market_id)??workspace.catalog.products[0];
 const origins=useMemo(()=>workspace.catalog.locations.filter(l=>l.market_id===product?.market_id),[workspace.catalog.locations,product?.market_id]);
 async function post(key:string,path:string,body:Record<string,unknown>){setBusy(key);setMessage(null);try{const response=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,idempotencyKey:crypto.randomUUID()})});const payload=(await response.json()) as ApiResult;if(!payload.ok)setMessage(payload.message??"Raahi could not confirm this action.");else{router.refresh();if(key==="draft")setForm(emptyForm);}}catch{setMessage("The network did not confirm this action. Please try again.");}finally{setBusy(null);}}
 function createDraft(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!product||!workspace.active_vehicle_id||origins.length===0)return;void post("draft","/api/trips/create-draft",{productId:product.product_id,vehicleId:workspace.active_vehicle_id,originLocationId:origins[0].location_id,destinationLocationId:form.destination,departureAt:new Date(form.departure).toISOString(),returnDepartureAt:new Date(form.returnDeparture).toISOString(),offeredSeats:form.seats,pricePerSeatInr:form.price,minConfirmationSeats:form.threshold,confirmationDeadline:new Date(form.deadline).toISOString(),itineraryContext:form.itinerary||null});}
 const previewDestination=workspace.catalog.locations.find(l=>l.location_id===form.destination)?.name;const previewReady=Boolean(previewDestination&&form.departure&&form.returnDeparture&&form.deadline);
 function fulfil(t:DriverTripOffering,action:string,bookingId?:string){const body:Record<string,unknown>={action,rideId:t.ride_id};if(bookingId)body.bookingId=bookingId;const gps=["ARRIVE","COMPLETE_OUTBOUND","COMPLETE_RETURN"].includes(action);if(!gps){void post(`${action}:${t.offering_id}`,"/api/driver/trips/fulfilment",body);return;}if(!navigator.geolocation){setMessage("Location access is required for this step.");return;}setBusy(`${action}:${t.offering_id}`);navigator.geolocation.getCurrentPosition(pos=>{setBusy(null);void post(`${action}:${t.offering_id}`,"/api/driver/trips/fulfilment",{...body,latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracyMeters:pos.coords.accuracy,capturedAt:new Date(pos.timestamp).toISOString()});},()=>{setBusy(null);setMessage("Raahi could not read a fresh location for this step.");},{enableHighAccuracy:true,maximumAge:0,timeout:15000});}
 return <div className="space-y-6">
  <section className="rounded-3xl bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-emerald-700">Create Raahi Trip</p><h2 className="mt-2 text-2xl font-semibold">Plan a shared day journey</h2><p className="mt-2 text-sm leading-6 text-zinc-600">Set the transport, destination wait and return plan deliberately. Raahi Trips are mobility, not bundled hotels, guides, meals or tickets.</p>{!workspace.active_vehicle?<p className="mt-4 rounded-2xl bg-amber-50 p-4 text-sm text-amber-900">Select an eligible active Vehicle before creating a Trip.</p>:workspace.operating_market_id!==product?.market_id?<p className="mt-4 rounded-2xl bg-amber-50 p-4 text-sm text-amber-900">Your verified Current Operating Market must match this Trip’s origin Market.</p>:product&&origins.length?<form onSubmit={createDraft} className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">From<input value={origins[0].name} disabled className="mt-1 w-full rounded-xl border border-zinc-200 bg-zinc-100 px-3 py-2.5"/></label><label className="text-sm font-medium">Destination<select required value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})} className="mt-1 w-full rounded-xl border border-zinc-300 bg-white px-3 py-2.5"><option value="">Choose destination</option>{workspace.catalog.locations.filter(l=>l.location_id!==origins[0].location_id).map(l=><option key={l.location_id} value={l.location_id}>{l.name}</option>)}</select></label>
  <label className="text-sm font-medium">Departure<input required type="datetime-local" value={form.departure} onChange={e=>setForm({...form,departure:e.target.value})} className="mt-1 w-full rounded-xl border border-zinc-300 px-3 py-2.5"/></label><label className="text-sm font-medium">Planned return departure<input required type="datetime-local" value={form.returnDeparture} onChange={e=>setForm({...form,returnDeparture:e.target.value})} className="mt-1 w-full rounded-xl border border-zinc-300 px-3 py-2.5"/></label>
  <label className="text-sm font-medium">Seats<input required type="number" min={1} max={workspace.active_vehicle.capacity} value={form.seats} onChange={e=>setForm({...form,seats:Number(e.target.value)})} className="mt-1 w-full rounded-xl border border-zinc-300 px-3 py-2.5"/></label><label className="text-sm font-medium">Price per seat (₹)<input required type="number" min={1} value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})} className="mt-1 w-full rounded-xl border border-zinc-300 px-3 py-2.5"/></label>
  <label className="text-sm font-medium">Minimum seats to confirm<input required type="number" min={1} max={form.seats} value={form.threshold} onChange={e=>setForm({...form,threshold:Number(e.target.value)})} className="mt-1 w-full rounded-xl border border-zinc-300 px-3 py-2.5"/></label><label className="text-sm font-medium">Confirmation deadline<input required type="datetime-local" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})} className="mt-1 w-full rounded-xl border border-zinc-300 px-3 py-2.5"/></label>
  <label className="sm:col-span-2 text-sm font-medium">Trip context<textarea rows={3} maxLength={1000} value={form.itinerary} onChange={e=>setForm({...form,itinerary:e.target.value})} placeholder="Transport, destination wait and return plan — no hotel, guide, meal or ticket promises." className="mt-1 w-full rounded-xl border border-zinc-300 px-3 py-2.5"/></label>
  {previewReady?<div className="sm:col-span-2 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-emerald-800">Preview before draft</p><p className="mt-2 font-semibold">{origins[0].name} → {previewDestination}</p><p className="mt-1 text-sm text-emerald-950">{formatTripDateTime(new Date(form.departure).toISOString())} · return {formatTripDateTime(new Date(form.returnDeparture).toISOString())}</p><p className="mt-1 text-sm text-emerald-950">₹{form.price}/seat · {form.seats} seats · confirms at {form.threshold} seats by {formatTripDateTime(new Date(form.deadline).toISOString())}</p><p className="mt-2 text-xs text-emerald-900">This remains a draft until you explicitly publish it.</p></div>:null}
  <div className="sm:col-span-2"><button type="submit" disabled={busy!==null||!previewReady} className="w-full rounded-xl bg-zinc-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Create draft for review</button></div></form>:<p className="mt-4 text-sm text-zinc-600">No Trip product is available for your operating Market.</p>}</section>
  <section className="rounded-3xl bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-zinc-500">Your Raahi Trips</p><h2 className="mt-2 text-2xl font-semibold">Filling first, commitment only at confirmation</h2><p className="mt-2 text-sm text-zinc-600">Before threshold you see aggregate demand only. Passenger identity appears only after the Trip is confirmed.</p><div className="mt-5 space-y-5">{workspace.offerings.map(t=><TripCard key={t.offering_id} trip={t} workspace={workspace} busy={busy} post={post} fulfil={fulfil}/>)}{workspace.offerings.length===0?<p className="rounded-2xl bg-zinc-50 p-4 text-sm text-zinc-600">No Raahi Trip created yet.</p>:null}</div></section>
  {message?<p className="rounded-2xl bg-red-50 p-4 text-sm text-red-700" role="status">{message}</p>:null}
 </div>;
}
function TripCard({trip:t,workspace,busy,post,fulfil}:{trip:DriverTripOffering;workspace:Workspace;busy:string|null;post:(key:string,path:string,body:Record<string,unknown>)=>Promise<void>;fulfil:(t:DriverTripOffering,action:string,bookingId?:string)=>void}){
 const terminal=["COMPLETED","DRIVER_CANCELLED","NOT_CONFIRMED","EXPIRED"].includes(t.status);
 const canCancel=!terminal&&(!t.ride_status||t.ride_status==="UPCOMING");
 const nextAction=t.ride_status==="UPCOMING"?["BEGIN_APPROACH","Start driving to origin"]:t.ride_status==="DRIVER_EN_ROUTE"?["ARRIVE","I’ve arrived at origin"]:t.ride_status==="DRIVER_ARRIVED"?["START_BOARDING","Start outbound boarding"]:t.ride_status==="READY_TO_DEPART"?["DEPART_OUTBOUND","Depart for destination"]:t.ride_status==="OUTBOUND_IN_PROGRESS"?["COMPLETE_OUTBOUND","Arrived at destination"]:t.ride_status==="WAITING_FOR_RETURN"?["START_RETURN_BOARDING","Start return boarding"]:t.ride_status==="RETURN_IN_PROGRESS"?["COMPLETE_RETURN","Complete return at origin"]:null;
 const filling=t.status==="FILLING";
 return <article className="rounded-2xl border border-zinc-200 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className={`text-xs font-semibold uppercase tracking-[0.12em] ${filling?"text-amber-700":"text-emerald-700"}`}>{t.display_status.replaceAll("_"," ")}</p><h3 className="mt-2 text-xl font-semibold">{t.origin_name} → {t.destination_name}</h3><p className="mt-1 text-sm text-zinc-600">{formatTripDateTime(t.departure_at)} · return {formatTripDateTime(t.return_departure_at)}</p><p className="mt-1 text-sm text-zinc-600">₹{t.price_per_seat_inr}/seat · {t.booked_seats}/{t.offered_seats} seats booked</p></div><div className="text-right">{filling?<><p className="font-semibold text-amber-800">{t.seats_needed_to_confirm} more seat{t.seats_needed_to_confirm===1?"":"s"} to confirm</p><p className="mt-1 text-xs text-zinc-500">Deadline {formatTripDateTime(t.confirmation_deadline)}</p></>:t.ride_status?<><p className="font-semibold">Trip confirmed</p><p className="mt-1 text-xs text-zinc-500">Ride · {t.ride_status.replaceAll("_"," ")}</p></>:null}</div></div>
  {t.itinerary_context?<p className="mt-4 rounded-2xl bg-zinc-50 p-4 text-sm leading-6 text-zinc-700">{t.itinerary_context}</p>:null}
  {t.status==="DRAFT"?<DraftEdit trip={t} workspace={workspace} busy={busy} post={post}/>:null}
  {t.status==="DRAFT"?<button type="button" disabled={busy!==null} onClick={()=>void post(`publish:${t.offering_id}`,"/api/trips/publish",{offeringId:t.offering_id})} className="mt-4 rounded-xl bg-zinc-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Publish Trip</button>:null}
  {t.bookings.length?<div className="mt-4 space-y-3">{t.bookings.map(b=><div key={b.trip_booking_id} className="rounded-2xl bg-zinc-50 p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold">{b.passenger_name}</p><p className="text-sm text-zinc-600">{b.seat_count} seat{b.seat_count===1?"":"s"} · {b.status.replaceAll("_"," ")}{b.passenger_phone?` · ${b.passenger_phone}`:""}</p>{b.ride_booking_status?<p className="mt-1 text-xs text-zinc-500">Outbound {b.ride_booking_status.replaceAll("_"," ")} · return {(b.return_status??"NOT APPLICABLE").replaceAll("_"," ")}</p>:null}</div><p className="font-semibold">₹{b.seat_count*b.price_per_seat_inr}</p></div>
   {t.ride_status==="BOARDING"&&b.ride_booking_id&&b.ride_booking_status==="ASSIGNED"?<div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={busy!==null} onClick={()=>fulfil(t,"BOARDED",b.ride_booking_id!)} className="rounded-xl bg-zinc-950 px-3 py-2 text-xs font-semibold text-white">Passenger boarded</button><button type="button" disabled={busy!==null} onClick={()=>fulfil(t,"NO_SHOW",b.ride_booking_id!)} className="rounded-xl border border-zinc-300 bg-white px-3 py-2 text-xs font-semibold">Report no-show after wait</button></div>:null}
   {t.ride_status==="RETURN_BOARDING"&&b.ride_booking_id&&b.ride_booking_status==="BOARDED"&&b.return_status==="PENDING"?<div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={busy!==null} onClick={()=>fulfil(t,"RETURN_BOARDED",b.ride_booking_id!)} className="rounded-xl bg-zinc-950 px-3 py-2 text-xs font-semibold text-white">Return boarded</button><button type="button" disabled={busy!==null} onClick={()=>fulfil(t,"RETURN_NO_SHOW",b.ride_booking_id!)} className="rounded-xl border border-zinc-300 bg-white px-3 py-2 text-xs font-semibold">Return no-show after wait</button></div>:null}
   {b.payment&&t.ride_id?<DriverPaymentCard payment={{payment_id:b.payment.payment_id,ride_id:t.ride_id,status:b.payment.status,amount_inr:b.payment.amount_inr,passenger_name:b.passenger_name,origin_name:t.origin_name,destination_name:t.destination_name,completed_at:null}}/>:null}</div>)}</div>:filling&&t.booked_seats>0?<p className="mt-4 rounded-2xl bg-amber-50 p-4 text-sm text-amber-900">{t.booked_seats} tentative seat{t.booked_seats===1?"":"s"} booked. Passenger identities stay private until confirmation.</p>:null}
  {nextAction?<button type="button" disabled={busy!==null} onClick={()=>fulfil(t,nextAction[0])} className="mt-4 rounded-xl bg-zinc-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{nextAction[1]}</button>:null}
  {canCancel?<button type="button" disabled={busy!==null} onClick={()=>void post(`cancel:${t.offering_id}`,"/api/driver/trips/cancel",{offeringId:t.offering_id})} className="mt-4 ml-2 rounded-xl border border-zinc-300 px-4 py-2.5 text-sm font-semibold">Cancel Trip</button>:null}
  {t.ride_id?<ReportIssue objectType="RIDE" objectId={t.ride_id}/>:null}
 </article>;
}
function DraftEdit({trip:t,workspace,busy,post}:{trip:DriverTripOffering;workspace:Workspace;busy:string|null;post:(key:string,path:string,body:Record<string,unknown>)=>Promise<void>}){
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!workspace.active_vehicle_id)return;const f=new FormData(e.currentTarget);void post(`update:${t.offering_id}`,"/api/trips/update",{offeringId:t.offering_id,vehicleId:workspace.active_vehicle_id,originLocationId:t.origin_location_id,destinationLocationId:String(f.get("destination")),departureAt:new Date(String(f.get("departure"))).toISOString(),returnDepartureAt:new Date(String(f.get("returnDeparture"))).toISOString(),offeredSeats:Number(f.get("seats")),pricePerSeatInr:Number(f.get("price")),minConfirmationSeats:Number(f.get("threshold")),confirmationDeadline:new Date(String(f.get("deadline"))).toISOString(),itineraryContext:String(f.get("itinerary")||"")||null});}
 return <details className="mt-4 rounded-2xl bg-zinc-50 p-4"><summary className="cursor-pointer text-sm font-semibold">Review or edit draft before publishing</summary><p className="mt-2 text-xs text-zinc-600">Once the first Passenger books, price and published terms are locked.</p><form onSubmit={submit} className="mt-4 grid gap-3 sm:grid-cols-2">
  <label className="text-xs font-medium">Destination<select name="destination" defaultValue={t.destination_location_id} className="mt-1 w-full rounded-xl border border-zinc-300 bg-white px-3 py-2">{workspace.catalog.locations.filter(l=>l.location_id!==t.origin_location_id).map(l=><option key={l.location_id} value={l.location_id}>{l.name}</option>)}</select></label>
  <label className="text-xs font-medium">Departure<input name="departure" type="datetime-local" defaultValue={tripLocalInputValue(t.departure_at)} required className="mt-1 w-full rounded-xl border border-zinc-300 px-3 py-2"/></label>
  <label className="text-xs font-medium">Return departure<input name="returnDeparture" type="datetime-local" defaultValue={tripLocalInputValue(t.return_departure_at)} required className="mt-1 w-full rounded-xl border border-zinc-300 px-3 py-2"/></label>
  <label className="text-xs font-medium">Confirmation deadline<input name="deadline" type="datetime-local" defaultValue={tripLocalInputValue(t.confirmation_deadline)} required className="mt-1 w-full rounded-xl border border-zinc-300 px-3 py-2"/></label>
  <label className="text-xs font-medium">Seats<input name="seats" type="number" min={1} max={workspace.active_vehicle?.capacity??12} defaultValue={t.offered_seats} required className="mt-1 w-full rounded-xl border border-zinc-300 px-3 py-2"/></label>
  <label className="text-xs font-medium">Price per seat (₹)<input name="price" type="number" min={1} defaultValue={t.price_per_seat_inr} required className="mt-1 w-full rounded-xl border border-zinc-300 px-3 py-2"/></label>
  <label className="text-xs font-medium">Minimum seats to confirm<input name="threshold" type="number" min={1} max={t.offered_seats} defaultValue={t.min_confirmation_seats} required className="mt-1 w-full rounded-xl border border-zinc-300 px-3 py-2"/></label>
  <label className="sm:col-span-2 text-xs font-medium">Trip context<textarea name="itinerary" rows={3} maxLength={1000} defaultValue={t.itinerary_context??""} className="mt-1 w-full rounded-xl border border-zinc-300 px-3 py-2"/></label>
  <button disabled={busy!==null} className="sm:col-span-2 rounded-xl bg-zinc-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Save draft</button>
 </form></details>;
}
