"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { PassengerPaymentCard } from "@/features/payment-support/PassengerPaymentCard";
import { ReportIssue } from "@/features/payment-support/ReportIssue";
import { formatTripDateTime } from "./format";
import type { TripOfferingView } from "./types";

type ApiResult={ok:boolean;message?:string};
export function TripOfferingActions({offering}:{offering:TripOfferingView}){
 const router=useRouter();const[seats,setSeats]=useState(1);const[busy,setBusy]=useState(false);const[message,setMessage]=useState<string|null>(null);
 async function post(path:string,body:Record<string,unknown>){setBusy(true);setMessage(null);try{const response=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,idempotencyKey:crypto.randomUUID()})});const payload=(await response.json()) as ApiResult;if(!payload.ok)setMessage(payload.message??"Raahi could not confirm this action.");else router.refresh();}catch{setMessage("The network did not confirm this action. Please try again.");}finally{setBusy(false);}}
 const b=offering.my_booking;const activeBooking=b&&["FILLING","CONFIRMED"].includes(b.status);const canBook=!activeBooking&&["FILLING","CONFIRMED"].includes(offering.status)&&offering.seats_left>0;
 return <div className="mt-6 space-y-5">
  {offering.status==="FILLING"?<section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-amber-800">Filling · not confirmed yet</p><p className="mt-2 text-lg font-semibold">{offering.seats_needed_to_confirm} more seat{offering.seats_needed_to_confirm===1?"":"s"} needed to confirm</p><p className="mt-2 text-sm leading-6 text-amber-950">Confirmation deadline: {formatTripDateTime(offering.confirmation_deadline)}. Your booking reserves capacity, but the journey is not guaranteed until the threshold is reached.</p></section>:null}
  {offering.status==="CONFIRMED"?<section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-emerald-800">Your trip can be booked with confidence</p><p className="mt-2 text-xl font-semibold">This Raahi Trip is confirmed</p><p className="mt-1 text-sm text-zinc-700">Later Passenger cancellations do not push it back into filling.</p></section>:null}
  {canBook?<section className="rounded-2xl border border-zinc-200 bg-zinc-50 p-5"><p className="text-sm font-semibold">{offering.status==="FILLING"?"Reserve seats while the Trip fills":"Book confirmed Trip seats"}</p><p className="mt-1 text-sm text-zinc-600">₹{offering.price_per_seat_inr} per seat · transport, destination wait and return.</p><div className="mt-4 flex flex-wrap items-end gap-3"><label className="text-sm font-medium">Seats<select value={seats} onChange={e=>setSeats(Number(e.target.value))} className="ml-2 rounded-xl border border-zinc-300 bg-white px-3 py-2">{Array.from({length:Math.min(offering.seats_left,4)},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select></label><button type="button" disabled={busy} onClick={()=>void post("/api/trips/book",{offeringId:offering.offering_id,seatCount:seats})} className="rounded-xl bg-zinc-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{offering.status==="FILLING"?"Reserve":"Book"} · ₹{seats*offering.price_per_seat_inr}</button></div></section>:null}
  {b?<section className={`rounded-2xl border p-5 ${b.status==="CONFIRMED"?"border-emerald-200 bg-emerald-50":b.status==="FILLING"?"border-amber-200 bg-amber-50":"border-zinc-200 bg-zinc-50"}`}><p className="text-xs font-semibold uppercase tracking-[0.12em] text-zinc-700">Your booking · {b.status.replaceAll("_"," ")}</p><p className="mt-2 text-lg font-semibold">{b.seat_count} seat{b.seat_count===1?"":"s"} · ₹{b.total_inr}</p>{b.status==="FILLING"?<p className="mt-2 text-sm text-amber-950">This is still a tentative booking. Raahi will not present it as guaranteed before the Trip confirms.</p>:null}{b.status==="NOT_CONFIRMED"?<p className="mt-2 text-sm text-zinc-700">The Trip did not reach its threshold by the deadline. This booking was released without a Passenger reliability penalty.</p>:null}{offering.driver_phone?<p className="mt-2 text-sm text-zinc-700">Driver contact: {offering.driver_phone}</p>:null}{["FILLING","CONFIRMED"].includes(b.status)&&(!offering.ride_status||offering.ride_status==="UPCOMING")?<button type="button" disabled={busy} onClick={()=>void post("/api/trips/cancel-booking",{tripBookingId:b.trip_booking_id})} className="mt-4 rounded-xl border border-zinc-300 bg-white px-4 py-2 text-sm font-semibold">Cancel booking</button>:null}</section>:null}
  {b?.payment&&offering.ride_id&&b.ride_booking_id?<PassengerPaymentCard payment={{...b.payment,ride_id:offering.ride_id,booking_id:b.ride_booking_id,dispute_case_id:b.payment.dispute_case_id??null}}/>:null}
  {offering.ride_id?<ReportIssue objectType="RIDE" objectId={offering.ride_id}/>:null}
  {message?<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700" role="status">{message}</p>:null}
 </div>;
}
