'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { CalendarClock, CheckCircle2, Loader2, MapPin, RefreshCw, Send, ShieldAlert, ShieldCheck, Users, X } from 'lucide-react';
import { toast } from 'sonner';
import { getDriverOutstationAreaPreferences, getDriverOutstationBookings, getDriverOutstationLeads, ignoreDriverOutstationRequest, sendDriverOutstationQuote, setDriverOutstationAreaPreference, withdrawDriverOutstationQuote, type DriverOutstationAreaPreference, type DriverOutstationBooking, type DriverOutstationLead } from '@/lib/outstationApi';

type QuoteDraft={price:string;tolls:boolean;parking:boolean;note:string};

export default function DriverOutstationContent(){
  const [areaPrefs,setAreaPrefs]=useState<DriverOutstationAreaPreference[]>([]); const [leads,setLeads]=useState<DriverOutstationLead[]>([]); const [bookings,setBookings]=useState<DriverOutstationBooking[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [drafts,setDrafts]=useState<Record<string,QuoteDraft>>({});
  const load=useCallback(async()=>{setLoading(true);try{const [a,l,b]=await Promise.all([getDriverOutstationAreaPreferences(),getDriverOutstationLeads(),getDriverOutstationBookings()]);setAreaPrefs(a);setLeads(l);setBookings(b);}catch(e:any){toast.error(e.message||'Could not load Outstation');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const draft=(lead:DriverOutstationLead)=>drafts[lead.request_id]||{price:lead.my_quote_price?String(lead.my_quote_price):'',tolls:false,parking:false,note:''};
  const setDraft=(id:string,patch:Partial<QuoteDraft>)=>setDrafts(d=>({...d,[id]:{...(d[id]||{price:'',tolls:false,parking:false,note:''}),...patch}}));
  const send=async(lead:DriverOutstationLead)=>{const d=draft(lead);const price=Number(d.price);if(!Number.isFinite(price)||price<=0)return toast.error('Enter a total quote');setBusy(`quote-${lead.request_id}`);try{await sendDriverOutstationQuote({requestId:lead.request_id,totalPrice:price,includesTolls:d.tolls,includesParking:d.parking,note:d.note});toast.success('Quote sent to Passenger');await load();}catch(e:any){toast.error(e.message);}finally{setBusy(null);}};
  const ignore=async(id:string)=>{setBusy(`ignore-${id}`);try{await ignoreDriverOutstationRequest(id);toast.success('Lead hidden');await load();}catch(e:any){toast.error(e.message);}finally{setBusy(null);}};
  const withdraw=async(quoteId:string)=>{if(!window.confirm('Withdraw this outstation quote?'))return;setBusy(`withdraw-${quoteId}`);try{await withdrawDriverOutstationQuote(quoteId);toast.success('Quote withdrawn');await load();}catch(e:any){toast.error(e.message);}finally{setBusy(null);}};
  const toggleArea=async(area:DriverOutstationAreaPreference,enabled:boolean)=>{setBusy(`area-${area.area_id}`);try{await setDriverOutstationAreaPreference(area.area_id,enabled);toast.success(enabled?`${area.area_name} Outstation leads enabled`:`${area.area_name} Outstation leads paused`);await load();}catch(e:any){toast.error(e.message);}finally{setBusy(null);}};
  return <div className="mx-auto max-w-screen-lg space-y-5 px-4 py-5 sm:px-6 sm:py-8">
    <section className="hero-surface"><p className="text-[11px] font-bold uppercase tracking-[0.14em] text-amber-200">Driver opportunities</p><h1 className="mt-2 text-2xl font-extrabold text-white sm:text-3xl">Choose where you want Outstation work</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-white/75">Select the pickup areas where you want trip enquiries. Outstation choices are separate from Shared Ride routes and never change your fixed-route FIFO position.</p></section>
    <section className="feature-card p-4 sm:p-5"><div><p className="section-label">Outstation areas</p><h2 className="mt-1 text-lg font-extrabold">Where do you want trip enquiries from?</h2><p className="mt-1 text-xs leading-relaxed text-muted-foreground">Choose independently from Shared Ride. This does not add you to Shared Ride FIFO.</p></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{areaPrefs.map(area=><label key={area.area_id} className={`flex items-center justify-between rounded-xl border px-3 py-3 ${area.subscribed?'border-primary bg-secondary/60':'border-border'}`}><span><span className="block text-sm font-bold">{area.area_name}</span><span className="text-[11px] text-muted-foreground">{area.state}{!area.is_active?' · paused by Raahi':''}</span></span><input type="checkbox" checked={area.subscribed} disabled={busy===`area-${area.area_id}`||(!area.is_active&&!area.subscribed)} onChange={e=>void toggleArea(area,e.target.checked)}/></label>)}</div>{areaPrefs.length===0&&!loading&&<p className="mt-3 text-xs text-muted-foreground">No Outstation service areas are available yet.</p>}</section>
    <section className="rounded-2xl border border-primary/20 bg-secondary/60 p-4"><div className="flex items-start gap-3"><ShieldCheck size={19} className="mt-0.5 shrink-0 text-primary"/><div><p className="text-sm font-extrabold">Verification unlocks quoting</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">Driving Licence, vehicle RC and car photos must all be verified before Raahi lets you send a price.</p><Link href="/driver-verification" className="mt-2 inline-block text-xs font-bold text-primary underline">Open Driver verification</Link></div></div></section>
    {bookings.length>0&&<section className="space-y-3"><div><p className="section-label">Accepted</p><h2 className="mt-1 text-lg font-extrabold">Confirmed Outstation work</h2></div>{bookings.map(b=><div key={b.quote_id} className="feature-card p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-extrabold">{b.origin_name} → {b.destination_text}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(b.departure_at).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})} · {b.passenger_count} passenger{b.passenger_count===1?'':'s'}</p>{b.pickup_text&&<p className="mt-1 text-xs text-muted-foreground">Pickup · {b.pickup_text}</p>}</div><span className="rounded-full bg-green-50 px-2.5 py-1 text-[10px] font-bold text-green-700">Accepted</span></div><div className="mt-3 rounded-2xl bg-green-50 p-3"><p className="text-sm font-extrabold text-green-900">₹{b.total_price.toLocaleString('en-IN')} · {b.passenger_name}</p><a href={`tel:${b.passenger_phone}`} className="mt-1 inline-block text-sm font-bold text-green-800 underline">Call Passenger · {b.passenger_phone}</a><p className="mt-1 text-xs text-green-800">{b.vehicle_number} · {b.includes_tolls?'Tolls included':'Tolls extra'} · {b.includes_parking?'Parking included':'Parking extra'}</p></div></div>)}</section>}
    <section className="space-y-3"><div className="flex items-end justify-between gap-3"><div><p className="section-label">Available leads</p><h2 className="mt-1 text-lg font-extrabold">Passengers looking for a car</h2></div><button onClick={load} className="btn-outline px-3 py-2"><RefreshCw size={14}/>Refresh</button></div>{loading&&<div className="flex justify-center py-10"><Loader2 className="animate-spin text-primary"/></div>}{!loading&&leads.length===0&&<div className="feature-card p-8 text-center text-sm text-muted-foreground">No matching outstation leads right now.</div>}{leads.map(lead=><LeadCard key={lead.request_id} lead={lead} draft={draft(lead)} setDraft={patch=>setDraft(lead.request_id,patch)} onSend={()=>send(lead)} onIgnore={()=>ignore(lead.request_id)} onWithdraw={()=>lead.my_quote_id&&withdraw(lead.my_quote_id)} busy={busy}/>)}</section>
  </div>;
}

function LeadCard({lead,draft,setDraft,onSend,onIgnore,onWithdraw,busy}:{lead:DriverOutstationLead;draft:QuoteDraft;setDraft:(p:Partial<QuoteDraft>)=>void;onSend:()=>void;onIgnore:()=>void;onWithdraw:()=>void;busy:string|null}){
  const eligible=lead.verification_complete&&lead.vehicle_capacity>=lead.passenger_count; const hasQuote=lead.my_quote_status==='OFFERED'&&Boolean(lead.my_quote_id);
  return <div className="feature-card p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-extrabold">{lead.origin_name} → {lead.destination_text}</p><div className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><CalendarClock size={13}/>{new Date(lead.departure_at).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</span><span className="inline-flex items-center gap-1"><Users size={13}/>{lead.passenger_count} passenger{lead.passenger_count===1?'':'s'}</span></div>{lead.pickup_text&&<p className="mt-1 text-xs text-muted-foreground">Pickup · {lead.pickup_text}</p>}<p className="mt-1 text-xs text-muted-foreground">{lead.travel_type==='ROUND_TRIP'?'Round trip':'One way'}{lead.notes?` · ${lead.notes}`:''}</p></div>{hasQuote?<span className="rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-bold text-blue-700">Quote sent</span>:<MapPin size={18} className="text-primary"/>}</div>
    {!lead.verification_complete&&<div className="mt-3 rounded-xl bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-800"><ShieldAlert size={14} className="mr-1 inline"/>Complete Driver verification before quoting.</div>}
    {lead.vehicle_capacity<lead.passenger_count&&<div className="mt-3 rounded-xl bg-red-50 px-3 py-2 text-xs font-semibold text-red-700">Your current vehicle has {lead.vehicle_capacity} passenger seats; this request needs {lead.passenger_count}.</div>}
    <div className="mt-4 grid gap-3 sm:grid-cols-[160px_1fr]"><label className="text-xs font-bold">Total quote ₹<input inputMode="numeric" value={draft.price} onChange={e=>setDraft({price:e.target.value.replace(/\D/g,'')})} placeholder="4500" className="input-field mt-1"/></label><label className="text-xs font-bold">Note <span className="font-normal text-muted-foreground">optional</span><input maxLength={300} value={draft.note} onChange={e=>setDraft({note:e.target.value})} placeholder="Pickup details or quote terms" className="input-field mt-1"/></label></div>
    <div className="mt-3 flex flex-wrap gap-3 text-xs"><label className="flex items-center gap-2"><input type="checkbox" checked={draft.tolls} onChange={e=>setDraft({tolls:e.target.checked})}/>Tolls included</label><label className="flex items-center gap-2"><input type="checkbox" checked={draft.parking} onChange={e=>setDraft({parking:e.target.checked})}/>Parking included</label></div>
    <div className="mt-4 flex gap-2"><button disabled={!eligible||busy===`quote-${lead.request_id}`} onClick={onSend} className="btn-primary flex-1">{busy===`quote-${lead.request_id}`?<Loader2 size={15} className="animate-spin"/>:<Send size={15}/>} {hasQuote?'Update quote':'Send quote'}</button>{hasQuote?<button disabled={busy===`withdraw-${lead.my_quote_id}`} onClick={onWithdraw} className="btn-outline text-red-600"><X size={15}/>Withdraw</button>:<button disabled={busy===`ignore-${lead.request_id}`} onClick={onIgnore} className="btn-outline">Ignore</button>}</div>
  </div>;
}
