import Link from "next/link";
import { TravelIntentActions } from "@/features/travel-intent/TravelIntentActions";
import { getMyTravelIntents } from "@/server/projections/travel-intent";

export default async function InterestsPage(){
 const projection=await getMyTravelIntents();
 if(projection.status==="UNAUTHENTICATED")return <main className="min-h-screen bg-zinc-100 px-5 py-10"><div className="mx-auto max-w-3xl rounded-3xl bg-white p-7 shadow-sm"><h1 className="text-2xl font-semibold">Your travel interests</h1><p className="mt-2 text-zinc-600">Sign in to see the journeys you have asked Raahi to remember.</p><Link href="/auth/sign-in" className="mt-5 inline-flex rounded-xl bg-zinc-950 px-4 py-2 text-sm font-semibold text-white">Sign in</Link></div></main>;
 return <main className="min-h-screen bg-zinc-100 px-5 py-10 text-zinc-950"><div className="mx-auto max-w-3xl"><Link href="/" className="text-sm font-semibold text-zinc-600">← Home</Link><p className="mt-8 text-sm font-semibold uppercase tracking-[0.16em] text-zinc-500">Demand Raahi remembers for you</p><h1 className="mt-2 text-3xl font-semibold">Your travel interests</h1><p className="mt-3 text-zinc-600">These are not bookings and do not hold seats. They help Raahi understand demand and optionally tell you when something useful becomes available.</p><div className="mt-7 space-y-4">
  {projection.intents.length===0?<div className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">No travel interests yet</h2><p className="mt-2 text-sm text-zinc-600">Search a journey. When Raahi does not have the right shared option, you can tell us you want to go.</p></div>:null}
  {projection.intents.map(intent=><article key={intent.intent_id} className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-zinc-500">{intent.status}</p><h2 className="mt-1 text-xl font-semibold">{intent.origin_name} → {intent.destination_name}</h2></div><p className="rounded-full bg-zinc-100 px-3 py-1 text-sm font-semibold">{intent.seat_count} seat{intent.seat_count===1?"":"s"}</p></div><p className="mt-3 text-sm text-zinc-600">{intent.desired_departure_at?new Date(intent.desired_departure_at).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Kolkata"}):"Any suitable time"} · {intent.acceptable_service_type.replaceAll("_"," ")}</p><p className="mt-2 text-sm text-zinc-600">Availability updates: {intent.notification_interest?"On":"Off"}</p><TravelIntentActions intent={intent}/></article>)}
 </div></div></main>;
}
