"use client";

import { useRouter } from "next/navigation";
import { useMemo, useState, type FormEvent } from "react";
import { DriverPaymentCard } from "@/features/payment-support/DriverPaymentCard";
import { ReportIssue } from "@/features/payment-support/ReportIssue";
import { formatCarpoolDateTime } from "./format";
import type { DriverCarpoolJourney, DriverCarpoolWorkspace as Workspace } from "./types";

type ApiResult={ok:boolean;message?:string};
function localInputValue(iso:string){const shifted=new Date(new Date(iso).getTime()+330*60000);return shifted.toISOString().slice(0,16);}

export function DriverCarpoolWorkspace({workspace}:{workspace:Workspace}){
 const router=useRouter();const[busy,setBusy]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);const product=workspace.catalog.products[0];
 const origins=useMemo(()=>workspace.catalog.locations.filter(l=>l.market_id===product?.market_id),[workspace.catalog.locations,product?.market_id]);
 async function post(key:string,path:string,body:Record<string,unknown>){setBusy(key);setMessage(null);try{const response=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,idempotencyKey:crypto.randomUUID()})});const payload=(await response.json()) as ApiResult;if(!payload.ok)setMessage(payload.message??"Raahi could not confirm this action.");else router.refresh();}catch{setMessage("The network did not confirm this action. Please try again.");}finally{setBusy(null);}}
 function publish(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!product||!workspace.active_vehicle_id)return;const f=new FormData(event.currentTarget);void post("publish","/api/carpool/publish",{productId:product.product_id,vehicleId:workspace.active_vehicle_id,originLocationId:String(f.get("origin")),destinationLocationId:String(f.get("destination")),departureAt:new Date(String(f.get("departure"))).toISOString(),offeredSeats:Number(f.get("seats")),contributionPerSeatInr:Number(f.get("price"))});}
 function fulfil(j:DriverCarpoolJourney,action:string,bookingId?:string){const body:Record<string,unknown>={action,rideId:j.ride_id};if(bookingId)body.bookingId=bookingId;const needsGps=action==="ARRIVE"||action==="COMPLETE";if(!needsGps){void post(`${action}:${j.journey_id}`,"/api/driver/carpool/fulfilment",body);return;}if(!navigator.geolocation){setMessage("Location access is required for this step.");return;}setBusy(`${action}:${j.journey_id}`);navigator.geolocation.getCurrentPosition(pos=>{setBusy(null);void post(`${action}:${j.journey_id}`,"/api/driver/carpool/fulfilment",{...body,latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracyMeters:pos.coords.accuracy,capturedAt:new Date(pos.timestamp).toISOString()});},()=>{setBusy(null);setMessage("Raahi could not read a fresh location for this step.");},{enableHighAccuracy:true,maximumAge:0,timeout:15000});}
 return <div className="space-y-6">
  <section className="rounded-3xl bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-emerald-700">Create Carpool</p><h2 className="mt-2 text-2xl font-semibold">I’m already going somewhere</h2><p className="mt-2 text-sm text-zinc-600">Publish only spare seats in a journey you are genuinely making. Publishing does not create a Passenger commitment; the first instant booking does.</p>{!workspace.active_vehicle?<p className="mt-4 rounded-2xl bg-amber-50 p-4 text-sm text-amber-900">Select an eligible active Vehicle in Driver setup before publishing Carpool.</p>:product?<form onSubmit={publish} className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">From<select name="origin" required className="mt-1 w-full rounded-xl border border-zinc-300 bg-white px-3 py-2.5">{origins.map(l=><option key={l.location_id} value={l.location_id}>{l.name}</option>)}</select></label><label className="text-sm font-medium">To<select name="destination" required className="mt-1 w-full rounded-xl border border-zinc-300 bg-white px-3 py-2.5">{workspace.catalog.locations.map(l=><option key={l.location_id} value={l.location_id}>{l.name}</option>)}</select></label><label className="text-sm font-medium">Departure<input name="departure" type="datetime-local" required className="mt-1 w-full rounded-xl border border-zinc-300 px-3 py-2.5"/></label><label className="text-sm font-medium">Spare seats<input name="seats" type="number" min={1} max={workspace.active_vehicle.capacity} defaultValue={2} required className="mt-1 w-full rounded-xl border border-zinc-300 px-3 py-2.5"/></label><label className="text-sm font-medium">Contribution per seat (₹)<input name="price" type="number" min={1} defaultValue={100} required className="mt-1 w-full rounded-xl border border-zinc-300 px-3 py-2.5"/></label><div className="flex items-end"><button type="submit" disabled={busy!==null} className="w-full rounded-xl bg-zinc-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Publish spare seats</button></div></form>:<p className="mt-4 text-sm text-zinc-600">No active Carpool product is available.</p>}</section>
  <section className="rounded-3xl bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-zinc-500">Your Carpool journeys</p><h2 className="mt-2 text-2xl font-semibold">One shared commitment timeline</h2><div className="mt-5 space-y-5">{workspace.journeys.map(j=><JourneyCard key={j.journey_id} journey={j} workspace={workspace} busy={busy} post={post} fulfil={fulfil}/>) }{workspace.journeys.length===0?<p className="rounded-2xl bg-zinc-50 p-4 text-sm text-zinc-600">No Carpool journey published yet.</p>:null}</div></section>
  {message?<p className="rounded-2xl bg-red-50 p-4 text-sm text-red-700" role="status">{message}</p>:null}
 </div>;
}

function JourneyCard({journey:j,workspace,busy,post,fulfil}:{journey:DriverCarpoolJourney;workspace:Workspace;busy:string|null;post:(key:string,path:string,body:Record<string,unknown>)=>Promise<void>;fulfil:(j:DriverCarpoolJourney,action:string,bookingId?:string)=>void}){
 const terminal=["COMPLETED","DRIVER_CANCELLED","EXPIRED"].includes(j.status);const canCancel=!terminal&&(!j.ride_status||j.ride_status==="UPCOMING");
 const nextAction=j.ride_status==="UPCOMING"?["BEGIN_APPROACH","Start driving to pickup"]:j.ride_status==="DRIVER_EN_ROUTE"?["ARRIVE","I’ve arrived"]:j.ride_status==="DRIVER_ARRIVED"?["START_BOARDING","Start boarding"]:j.ride_status==="READY_TO_DEPART"?["DEPART","Depart"]:j.ride_status==="IN_PROGRESS"?["COMPLETE","Complete at destination"]:null;
 return <article className="rounded-2xl border border-zinc-200 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-emerald-700">{j.status.replaceAll("_"," ")}</p><h3 className="mt-2 text-xl font-semibold">{j.origin_name} → {j.destination_name}</h3><p className="mt-1 text-sm text-zinc-600">{formatCarpoolDateTime(j.departure_at)} · ₹{j.contribution_per_seat_inr}/seat</p></div><div className="text-right"><p className="font-semibold">{j.booked_seats}/{j.offered_seats} seats booked</p>{j.ride_status?<p className="mt-1 text-xs text-zinc-500">Ride · {j.ride_status.replaceAll("_"," ")}</p>:<p className="mt-1 text-xs text-zinc-500">No Passenger commitment yet</p>}</div></div>
  {j.pending_change?<div className="mt-4 rounded-2xl bg-amber-50 p-4 text-sm text-amber-900"><p className="font-semibold">Change awaiting Passenger consent</p><p className="mt-1">{j.pending_change.proposed_destination_name} · {formatCarpoolDateTime(j.pending_change.proposed_departure_at)} · {j.pending_change.pending_responses??0} response(s) pending</p></div>:null}
  {!j.commitment_id&&j.status==="PUBLISHED"?<UncommittedEdit j={j} workspace={workspace} busy={busy} post={post}/>:j.commitment_id&&j.ride_status==="UPCOMING"&&!j.pending_change?<MaterialChange j={j} workspace={workspace} busy={busy} post={post}/>:null}
  {j.bookings.length?<div className="mt-4 space-y-3">{j.bookings.map(b=><div key={b.carpool_booking_id} className="rounded-2xl bg-zinc-50 p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold">{b.passenger_name}</p><p className="text-sm text-zinc-600">{b.seat_count} seat{b.seat_count===1?"":"s"} · {b.status.replaceAll("_"," ")}{b.passenger_phone?` · ${b.passenger_phone}`:""}</p></div><p className="font-semibold">₹{b.seat_count*b.contribution_per_seat_inr}</p></div>{j.ride_status==="BOARDING"&&b.status==="ACTIVE"?<div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={busy!==null} onClick={()=>fulfil(j,"BOARDED",b.ride_booking_id)} className="rounded-xl bg-zinc-950 px-3 py-2 text-xs font-semibold text-white">Passenger boarded</button><button type="button" disabled={busy!==null} onClick={()=>fulfil(j,"NO_SHOW",b.ride_booking_id)} className="rounded-xl border border-zinc-300 bg-white px-3 py-2 text-xs font-semibold">Report no-show after wait</button></div>:null}{b.payment&&j.ride_id?<DriverPaymentCard payment={{payment_id:b.payment.payment_id,ride_id:j.ride_id,status:b.payment.status,amount_inr:b.payment.amount_inr,passenger_name:b.passenger_name,origin_name:j.origin_name,destination_name:j.destination_name,completed_at:null}}/>:null}</div>)}</div>:null}
  {nextAction?<button type="button" disabled={busy!==null} onClick={()=>fulfil(j,nextAction[0])} className="mt-4 rounded-xl bg-zinc-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{nextAction[1]}</button>:null}
  {canCancel?<button type="button" disabled={busy!==null} onClick={()=>void post(`cancel:${j.journey_id}`,"/api/driver/carpool/cancel",{journeyId:j.journey_id})} className="mt-4 ml-2 rounded-xl border border-zinc-300 px-4 py-2.5 text-sm font-semibold">Cancel journey</button>:null}
  {j.ride_id?<ReportIssue objectType="RIDE" objectId={j.ride_id}/>:null}
 </article>;
}

function UncommittedEdit({j,workspace,busy,post}:{j:DriverCarpoolJourney;workspace:Workspace;busy:string|null;post:(key:string,path:string,body:Record<string,unknown>)=>Promise<void>}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);void post(`update:${j.journey_id}`,"/api/carpool/update",{journeyId:j.journey_id,destinationLocationId:String(f.get("destination")),departureAt:new Date(String(f.get("departure"))).toISOString(),offeredSeats:Number(f.get("seats")),contributionPerSeatInr:Number(f.get("price"))});}return <details className="mt-4 rounded-2xl bg-zinc-50 p-4"><summary className="cursor-pointer text-sm font-semibold">Edit before anyone books</summary><form onSubmit={submit} className="mt-4 grid gap-3 sm:grid-cols-2"><select name="destination" defaultValue={j.destination_location_id} className="rounded-xl border border-zinc-300 bg-white px-3 py-2">{workspace.catalog.locations.map(l=><option key={l.location_id} value={l.location_id}>{l.name}</option>)}</select><input name="departure" type="datetime-local" defaultValue={localInputValue(j.departure_at)} className="rounded-xl border border-zinc-300 px-3 py-2"/><input name="seats" type="number" min={1} defaultValue={j.offered_seats} className="rounded-xl border border-zinc-300 px-3 py-2"/><input name="price" type="number" min={1} defaultValue={j.contribution_per_seat_inr} className="rounded-xl border border-zinc-300 px-3 py-2"/><button disabled={busy!==null} className="rounded-xl bg-zinc-950 px-4 py-2 text-sm font-semibold text-white">Save uncommitted terms</button></form></details>;}
function MaterialChange({j,workspace,busy,post}:{j:DriverCarpoolJourney;workspace:Workspace;busy:string|null;post:(key:string,path:string,body:Record<string,unknown>)=>Promise<void>}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);void post(`change:${j.journey_id}`,"/api/driver/carpool/change",{journeyId:j.journey_id,destinationLocationId:String(f.get("destination")),departureAt:new Date(String(f.get("departure"))).toISOString()});}return <details className="mt-4 rounded-2xl bg-amber-50 p-4"><summary className="cursor-pointer text-sm font-semibold text-amber-900">Need to change time or destination?</summary><p className="mt-2 text-xs text-amber-900">Booked Passengers keep their original terms until they consent. Price and booked capacity stay locked.</p><form onSubmit={submit} className="mt-3 grid gap-3 sm:grid-cols-2"><select name="destination" defaultValue={j.destination_location_id} className="rounded-xl border border-amber-300 bg-white px-3 py-2">{workspace.catalog.locations.map(l=><option key={l.location_id} value={l.location_id}>{l.name}</option>)}</select><input name="departure" type="datetime-local" defaultValue={localInputValue(j.departure_at)} className="rounded-xl border border-amber-300 px-3 py-2"/><button disabled={busy!==null} className="rounded-xl bg-zinc-950 px-4 py-2 text-sm font-semibold text-white">Ask Passengers to re-consent</button></form></details>;}
