'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowRight, CalendarClock, CarFront, CheckCircle2, Loader2, MapPin, RefreshCw, ShieldCheck, Users } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '@/contexts/AuthContext';
import { acceptOutstationQuote, cancelOutstationRequest, createOutstationRequest, getDriverCarPhotoUrls, getMyOutstationQuotes, getMyOutstationRequests, getOutstationServiceAreas, type OutstationArea, type OutstationQuote, type OutstationRequest } from '@/lib/outstationApi';
import { useLegalAcceptanceGate } from '@/components/legal/LegalAcceptanceGate';
import { useRegulatoryLaunchGate } from '@/components/launch/RegulatoryLaunchGate';

function localInput(date:Date){const p=(n:number)=>String(n).padStart(2,'0');return `${date.getFullYear()}-${p(date.getMonth()+1)}-${p(date.getDate())}T${p(date.getHours())}:${p(date.getMinutes())}`;}

export default function OutstationContent(){
  const router=useRouter(); const {user,profile,loading:authLoading}=useAuth(); const {guard:guardLegal,dialog:legalDialog}=useLegalAcceptanceGate('passenger'); const {guard:guardLaunch,dialog:launchDialog}=useRegulatoryLaunchGate();
  const [areas,setAreas]=useState<OutstationArea[]>([]); const [requests,setRequests]=useState<OutstationRequest[]>([]); const [quotes,setQuotes]=useState<Record<string,OutstationQuote[]>>({});
  const [originArea,setOriginArea]=useState(''); const [pickupText,setPickupText]=useState(''); const [destination,setDestination]=useState(''); const [travelType,setTravelType]=useState<'ONE_WAY'|'ROUND_TRIP'>('ONE_WAY');
  const [departure,setDeparture]=useState(localInput(new Date(Date.now()+2*60*60*1000))); const [returnAt,setReturnAt]=useState(localInput(new Date(Date.now()+26*60*60*1000)));
  const [passengerCount,setPassengerCount]=useState(1); const [notes,setNotes]=useState(''); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true);

  const load=useCallback(async()=>{setLoading(true);try{const [a,r]=await Promise.all([getOutstationServiceAreas(),user&&profile?.role==='passenger'?getMyOutstationRequests():Promise.resolve([])]);setAreas(a);setRequests(r);setOriginArea(current=>current||a[0]?.area_id||'');}catch(e:any){toast.error(e.message||'Could not load Outstation');}finally{setLoading(false);}},[profile?.role,user]);
  useEffect(()=>{if(!authLoading) void load();},[authLoading,load]);
  const openCount=useMemo(()=>requests.filter(r=>r.status==='OPEN').length,[requests]);

  const submit=async(e:FormEvent)=>{e.preventDefault();if(!user){router.push('/login');return;}if(profile?.role!=='passenger')return toast.error('Use a Passenger account to request an outstation car');try{await guardLaunch(async()=>{await guardLegal(async()=>{setBusy(true);try{await createOutstationRequest({originAreaId:originArea,pickupText,destination,travelType,departureAt:new Date(departure).toISOString(),returnAt:travelType==='ROUND_TRIP'?new Date(returnAt).toISOString():null,passengerCount,notes});toast.success('Outstation request sent to eligible Raahi drivers');setDestination('');setPickupText('');setNotes('');await load();}finally{setBusy(false);}});});}catch(e:any){toast.error(e.message||'Could not check launch or booking access.');}};
  const showQuotes=async(requestId:string)=>{try{const rows=await getMyOutstationQuotes(requestId);setQuotes(q=>({...q,[requestId]:rows}));}catch(e:any){toast.error(e.message);}};
  const accept=async(quote:OutstationQuote)=>{if(!window.confirm(`Choose ${quote.driver_name} for ₹${quote.total_price.toLocaleString('en-IN')} total? Other quotes will close.`))return;try{await guardLaunch(async()=>{await guardLegal(async()=>{setBusy(true);try{await acceptOutstationQuote(quote.quote_id);toast.success('Driver selected. Contact details are now available.');await load();}finally{setBusy(false);}});});}catch(e:any){toast.error(e.message||'Could not check launch or booking access.');}};
  const cancel=async(id:string)=>{if(!window.confirm('Cancel this outstation request?'))return;setBusy(true);try{await cancelOutstationRequest(id);toast.success('Outstation request cancelled');await load();}catch(e:any){toast.error(e.message);}finally{setBusy(false);}};

  return <><div className="page-shell space-y-5">
    <div className="grid grid-cols-2 rounded-2xl bg-muted p-1 text-sm font-bold"><Link href="/" className="rounded-xl px-3 py-2.5 text-center text-muted-foreground">Shared Ride</Link><span className="rounded-xl bg-card px-3 py-2.5 text-center text-primary card-shadow-sm">Outstation</span></div>
    <section className="hero-surface"><p className="text-[11px] font-bold uppercase tracking-[0.14em] text-amber-200">Raahi Outstation</p><h1 className="mt-2 text-2xl font-extrabold text-white sm:text-3xl">Request a car. Compare verified local drivers.</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-white/75">Choose a Raahi pickup area, add the exact pickup point and enter any destination. Eligible drivers can send a total quote; you choose one only when you are ready.</p></section>
    <section className="rounded-2xl border border-green-200 bg-green-50 p-4"><div className="flex gap-3"><ShieldCheck className="mt-0.5 shrink-0 text-green-700" size={19}/><div><p className="text-sm font-extrabold text-green-900">Quotes come only from fully verified Drivers</p><p className="mt-1 text-xs leading-relaxed text-green-800">Raahi checks Driving Licence, vehicle RC and car photos for Passenger trust, and separately requires launch-compliance checks such as vehicle permit, fitness, insurance and PUC before a Driver can quote. Raw compliance documents stay private; you see safe verification status, vehicle details and approved car photos.</p></div></div></section>

    <form onSubmit={submit} className="feature-card space-y-4 p-4 sm:p-5">
      <div><p className="section-label">New request</p><h2 className="mt-1 text-lg font-extrabold">Where do you want to go?</h2></div>
      <div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">Pickup area<select required value={originArea} onChange={e=>setOriginArea(e.target.value)} className="input-field mt-1"><option value="">Choose area</option>{areas.map(a=><option key={a.area_id} value={a.area_id}>{a.area_name}</option>)}</select></label><label className="text-xs font-bold">Exact pickup<input required maxLength={180} value={pickupText} onChange={e=>setPickupText(e.target.value)} placeholder="Chas, Sector 4, station, home…" className="input-field mt-1"/></label></div><label className="text-xs font-bold">Destination<input required maxLength={160} value={destination} onChange={e=>setDestination(e.target.value)} placeholder="Ranchi, Patna, Kolkata…" className="input-field mt-1"/></label>
      <div className="grid grid-cols-2 gap-2"><button type="button" onClick={()=>setTravelType('ONE_WAY')} className={`rounded-xl border px-3 py-2 text-sm font-bold ${travelType==='ONE_WAY'?'border-primary bg-secondary text-primary':'border-border'}`}>One way</button><button type="button" onClick={()=>setTravelType('ROUND_TRIP')} className={`rounded-xl border px-3 py-2 text-sm font-bold ${travelType==='ROUND_TRIP'?'border-primary bg-secondary text-primary':'border-border'}`}>Round trip</button></div>
      <div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">Departure<input required type="datetime-local" value={departure} onChange={e=>setDeparture(e.target.value)} className="input-field mt-1"/></label>{travelType==='ROUND_TRIP'&&<label className="text-xs font-bold">Return<input required type="datetime-local" value={returnAt} onChange={e=>setReturnAt(e.target.value)} className="input-field mt-1"/></label>}</div>
      <label className="text-xs font-bold">Passengers<select value={passengerCount} onChange={e=>setPassengerCount(Number(e.target.value))} className="input-field mt-1">{Array.from({length:8},(_,i)=>i+1).map(n=><option key={n} value={n}>{n}</option>)}</select></label>
      <label className="text-xs font-bold">Notes <span className="font-normal text-muted-foreground">optional</span><textarea rows={3} maxLength={500} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Luggage, pickup details or anything useful for the Driver" className="input-field mt-1 resize-y"/></label>
      <button disabled={busy||!originArea||pickupText.trim().length<2} className="btn-primary w-full py-3">{busy?<Loader2 size={17} className="animate-spin"/>:<CarFront size={17}/>}Request prices</button>
      {!user&&<p className="text-center text-xs text-muted-foreground">You can plan here first. Raahi will ask you to sign in before sending the request.</p>}
    </form>

    {user&&profile?.role==='passenger'&&<section className="space-y-3"><div className="flex items-end justify-between"><div><p className="section-label">My Outstation</p><h2 className="mt-1 text-lg font-extrabold">Requests & quotes</h2></div><button onClick={load} className="btn-outline px-3 py-2"><RefreshCw size={14}/>Refresh</button></div>{loading&&<div className="flex justify-center py-8"><Loader2 className="animate-spin text-primary"/></div>}{!loading&&requests.length===0&&<div className="feature-card p-6 text-center text-sm text-muted-foreground">No outstation requests yet.</div>}{requests.map(r=><RequestCard key={r.request_id} request={r} quotes={quotes[r.request_id]} onShowQuotes={()=>showQuotes(r.request_id)} onAccept={accept} onCancel={()=>cancel(r.request_id)} busy={busy}/>) }{openCount>0&&<p className="text-[11px] text-muted-foreground">Open requests are leads only. Nothing is booked until you accept one Driver quote.</p>}</section>}
  </div>{launchDialog}{legalDialog}</>;
}

function RequestCard({request,quotes,onShowQuotes,onAccept,onCancel,busy}:{request:OutstationRequest;quotes?:OutstationQuote[];onShowQuotes:()=>void;onAccept:(q:OutstationQuote)=>void;onCancel:()=>void;busy:boolean}){
  const accepted=request.status==='ACCEPTED'; return <div className="feature-card p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-primary">{request.origin_name} → {request.destination_text}</p><p className="mt-1 text-sm font-extrabold">{new Date(request.departure_at).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</p><p className="mt-1 text-xs text-muted-foreground">{request.travel_type==='ROUND_TRIP'?'Round trip':'One way'} · {request.passenger_count} passenger{request.passenger_count===1?'':'s'}</p>{request.pickup_text&&<p className="mt-1 text-xs text-muted-foreground">Pickup · {request.pickup_text}</p>}</div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${accepted?'bg-green-50 text-green-700':request.status==='OPEN'?'bg-blue-50 text-blue-700':'bg-muted text-muted-foreground'}`}>{request.status}</span></div>
    {accepted&&<div className="mt-3 rounded-2xl border border-green-200 bg-green-50 p-3"><p className="text-sm font-extrabold text-green-900">₹{request.accepted_price?.toLocaleString('en-IN')} · {request.accepted_driver_name}</p><p className="mt-1 text-xs text-green-800">{request.accepted_vehicle_model||'Vehicle'} · {request.accepted_vehicle_number}</p>{request.accepted_driver_phone&&<a href={`tel:${request.accepted_driver_phone}`} className="mt-2 inline-block text-sm font-bold text-green-800 underline">Call Driver · {request.accepted_driver_phone}</a>}</div>}
    {request.status==='OPEN'&&<div className="mt-3 flex gap-2"><button onClick={onShowQuotes} className="btn-primary flex-1">{request.quote_count>0?`View ${request.quote_count} quote${request.quote_count===1?'':'s'}`:'Check quotes'}<ArrowRight size={15}/></button><button disabled={busy} onClick={onCancel} className="btn-outline text-red-600">Cancel</button></div>}
    {quotes&&<div className="mt-4 space-y-3">{quotes.length===0?<div className="rounded-2xl bg-muted p-4 text-center text-xs text-muted-foreground">No Driver quotes yet. Raahi will show them here as eligible Drivers respond.</div>:quotes.map(q=><QuoteCard key={q.quote_id} quote={q} onAccept={()=>onAccept(q)} disabled={busy||request.status!=='OPEN'}/>)}</div>}
  </div>;
}

function QuoteCard({quote,onAccept,disabled}:{quote:OutstationQuote;onAccept:()=>void;disabled:boolean}){
  const [photos,setPhotos]=useState<string[]>([]); useEffect(()=>{if(quote.car_photos_verified) void getDriverCarPhotoUrls(quote.driver_id).then(setPhotos).catch(()=>setPhotos([]));},[quote.driver_id,quote.car_photos_verified]);
  return <div className="rounded-2xl border border-border p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-lg font-extrabold">₹{quote.total_price.toLocaleString('en-IN')}</p><p className="text-sm font-bold">{quote.driver_name} · {quote.vehicle_model||quote.vehicle_type||'Car'}</p><p className="mt-1 text-xs text-muted-foreground">{quote.vehicle_number} · up to {quote.vehicle_capacity} passengers</p></div><ShieldCheck size={20} className="text-green-700"/></div>
    <div className="mt-3 flex flex-wrap gap-1.5"><Badge text="Driving Licence verified" ok={quote.driving_licence_verified}/><Badge text="Vehicle RC verified" ok={quote.vehicle_rc_verified}/><Badge text="Car photos verified" ok={quote.car_photos_verified}/></div>
    {photos.length>0&&<div className="mt-3 flex gap-2 overflow-x-auto">{photos.map((src,i)=><img key={src} src={src} alt={`Verified car photo ${i+1}`} className="h-24 w-32 shrink-0 rounded-xl object-cover"/>)}</div>}
    <div className="mt-3 text-xs text-muted-foreground"><p>{quote.includes_tolls?'Tolls included':'Tolls not included'} · {quote.includes_parking?'Parking included':'Parking not included'}</p>{quote.driver_note&&<p className="mt-1 text-foreground">{quote.driver_note}</p>}</div>
    {quote.quote_status==='ACCEPTED'?<div className="mt-3 rounded-xl bg-green-50 px-3 py-2 text-xs font-bold text-green-800"><CheckCircle2 size={14} className="mr-1 inline"/>Selected Driver{quote.driver_phone?` · ${quote.driver_phone}`:''}</div>:<button disabled={disabled||!quote.fully_verified} onClick={onAccept} className="btn-primary mt-3 w-full">Choose this car</button>}
  </div>;
}
function Badge({text,ok}:{text:string;ok:boolean}){return <span className={`rounded-full px-2 py-1 text-[10px] font-bold ${ok?'bg-green-50 text-green-700':'bg-muted text-muted-foreground'}`}>{ok?'✓':'•'} {text}</span>}
