import Link from "next/link";
import { MarketOpportunityReviewButton } from "@/features/travel-intent/MarketOpportunityReviewButton";
import { getMarketIntelligenceContext, getMarketOpportunitySignals } from "@/server/projections/travel-intent";

export default async function AdminPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const params=await searchParams;const requested=Array.isArray(params.market)?params.market[0]:params.market;const context=await getMarketIntelligenceContext();
 if(context.status==="UNAUTHENTICATED")return <main className="min-h-screen bg-zinc-100 px-5 py-10"><div className="mx-auto max-w-3xl rounded-3xl bg-white p-7 shadow-sm"><h1 className="text-2xl font-semibold">Market intelligence</h1><p className="mt-2 text-zinc-600">Sign in with an authorized Admin account.</p><Link href="/auth/sign-in" className="mt-5 inline-flex rounded-xl bg-zinc-950 px-4 py-2 text-sm font-semibold text-white">Sign in</Link></div></main>;
 if(context.status==="NOT_ADMIN")return <main className="min-h-screen bg-zinc-100 px-5 py-10"><div className="mx-auto max-w-3xl rounded-3xl bg-white p-7 shadow-sm"><h1 className="text-2xl font-semibold">Admin access required</h1><p className="mt-2 text-zinc-600">This workspace is scoped to authorized Market, State or Platform operations.</p></div></main>;
 const selected=context.markets.find(m=>m.market_id===requested)??context.markets[0];const signals=selected?await getMarketOpportunitySignals(selected.market_id):{status:"READY" as const,signals:[]};
 return <main className="min-h-screen bg-zinc-100 px-5 py-10 text-zinc-950"><div className="mx-auto max-w-5xl">
  <p className="text-sm font-semibold uppercase tracking-[0.18em] text-zinc-500">Raahi operations</p><h1 className="mt-2 text-3xl font-semibold">Where should this Market grow next?</h1>
  <p className="mt-3 max-w-3xl text-zinc-600">Raahi surfaces aggregate demand evidence. Reviewing an opportunity does not create a Corridor, Product, booking or Driver commitment.</p><Link href="/admin/businesses" className="mt-4 inline-flex rounded-xl border border-zinc-300 bg-white px-4 py-2 text-sm font-semibold">Businesses · Local Offers -&gt;</Link>
  <nav className="mt-6 flex flex-wrap gap-2">{context.markets.map(m=><Link key={m.market_id} href={`/admin?market=${m.market_id}`} className={`rounded-xl border px-4 py-2 text-sm font-semibold ${selected?.market_id===m.market_id?"border-zinc-950 bg-zinc-950 text-white":"border-zinc-300 bg-white"}`}>{m.name}</Link>)}</nav>
  <section className="mt-7 space-y-4">
   {signals.status!=="READY"?<div className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Market intelligence unavailable</h2><p className="mt-2 text-sm text-zinc-600">Raahi could not load this Market with your current scope.</p></div>:null}
   {signals.status==="READY"&&signals.signals.length===0?<div className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">No emerging corridor signals yet</h2><p className="mt-2 text-sm text-zinc-600">Meaningful Passenger Travel Intents will appear here as aggregate evidence.</p></div>:null}
   {signals.status==="READY"?signals.signals.map(s=><article key={s.opportunity_id} className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.13em] text-zinc-500">{s.status.replaceAll("_"," ")}</p><h2 className="mt-1 text-xl font-semibold">{s.origin_name} ΓåÆ {s.destination_name}</h2></div>{s.status==="DEMAND_SIGNALLED"?<MarketOpportunityReviewButton opportunityId={s.opportunity_id}/>:<p className="rounded-full bg-amber-50 px-3 py-1 text-sm font-semibold text-amber-800">Human review started</p>}</div><div className="mt-5 grid gap-3 sm:grid-cols-4"><Metric label="Travel intents" value={s.intent_count}/><Metric label="Seats wanted" value={s.seat_demand}/><Metric label="Next 7 days" value={s.desired_next_7d}/><Metric label="Next 30 days" value={s.desired_next_30d}/></div><p className="mt-4 text-sm text-zinc-600">{s.notification_interest_count} traveller{s.notification_interest_count===1?"":"s"} asked to hear if something useful becomes available. Passenger identity, phone and journey history are not exposed here.</p></article>):null}
  </section>
 </div></main>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl bg-zinc-50 p-4"><p className="text-xs font-medium uppercase tracking-[0.1em] text-zinc-500">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>;}
