import LegalDocumentPage from '@/components/legal/LegalDocumentPage';

export default function TermsPage() {
  return <LegalDocumentPage title="Terms of Service" version="2026-08-31-v1" intro="These Terms govern use of Raahi for shared local rides, Outstation requests and related account features. Browsing is open; acceptance is required before your first booking action.">
    <section><h2>1. What Raahi does</h2><p>Raahi is a local mobility coordination service. It helps passengers discover shared rides or request Outstation quotes from independent local Drivers. Raahi does not itself drive, own or operate the vehicle used for a trip.</p></section>
    <section><h2>2. Accounts and eligibility</h2><ul><li>Use accurate account information and keep access to your Google account and verified phone secure.</li><li>Passenger booking actions require a verified mobile number.</li><li>Raahi may restrict an account for fraud, abuse, unsafe conduct, repeated no-shows or misuse of the service.</li><li>Do not use Raahi if you are legally unable to enter into these Terms.</li></ul></section>
    <section><h2>3. Shared Ride bookings</h2><p>Shared Ride availability, seat holds, route progress and fares are shown from Raahi's live service state. A seat request is not final until the applicable booking state confirms it. Exact-seat requests are handled together or not at all.</p><p>Route fares shown in Raahi are service estimates or configured fares for that ride. Unless Raahi explicitly states otherwise, payment is made directly to the Driver.</p></section>
    <section><h2>4. Outstation requests and quotes</h2><p>An Outstation request is a lead, not a confirmed booking. Eligible Drivers may quote a total price. Nothing is booked until you choose a Driver quote. The accepted quote records the Driver, vehicle and quoted amount; tolls, parking and other inclusions are shown with the quote.</p></section>
    <section><h2>5. Driver and vehicle verification</h2><p>Raahi may verify a Driver's Driving Licence, vehicle RC and car photos before enabling certain features. A verified badge means Raahi recorded the required documents as verified at the relevant time. It is not a guarantee of future conduct, vehicle condition, driving quality or trip outcome.</p></section>
    <section><h2>6. Your conduct and safety</h2><ul><li>Treat Drivers, passengers and Raahi staff respectfully.</li><li>Do not use the service for unlawful, dangerous, abusive or fraudulent activity.</li><li>Follow seat capacity and safety requirements and do not pressure a Driver to drive unsafely.</li><li>Raahi is not an emergency service. Contact the appropriate emergency service when urgent assistance is required.</li></ul></section>
    <section><h2>7. Cancellations, no-shows and disputes</h2><p>Passengers and Drivers should cancel promptly when plans change. Repeated abuse, false requests, no-shows or payment disputes may affect account access. Where Raahi provides support, it may review service records and facilitate communication, but direct ride payments remain between Passenger and Driver unless Raahi expressly introduces another payment arrangement.</p></section>
    <section><h2>8. Availability and changes</h2><p>Raahi may change, pause or discontinue routes, service areas or features. Availability depends on local Driver supply, network connectivity, GPS and other third-party systems. Raahi does not promise that a Driver or seat will always be available.</p></section>
    <section><h2>9. Responsibility and liability</h2><p>To the extent permitted by applicable law, Raahi is responsible for operating the coordination service with reasonable care but is not the transport operator for independent Driver trips. Nothing in these Terms excludes rights or liabilities that cannot lawfully be excluded.</p></section>
    <section><h2>10. Governing law and updates</h2><p>These Terms are governed by applicable laws of India. Disputes are subject to the jurisdiction of competent courts in India as permitted by law. If Raahi materially changes these Terms, transactional access may require acceptance of a new version.</p></section>
  </LegalDocumentPage>;
}
