import LegalDocumentPage from '@/components/legal/LegalDocumentPage';

export default function PrivacyPage() {
  return <LegalDocumentPage title="Privacy Policy" version="2026-08-31-v1" intro="This Policy explains the personal data Raahi uses to provide local ride coordination, Driver verification, safety and support. Acceptance of the current policy is recorded before transactional use.">
    <section><h2>1. Data Raahi uses</h2><ul><li>Google account identity, display name and account identifiers used for sign-in.</li><li>Verified mobile number and verification status.</li><li>Ride requests, routes, stops, seat selections, Outstation pickup/destination details, quotes and booking state.</li><li>Driver profile, vehicle details and verification records including Driving Licence, RC and approved car photos.</li><li>GPS/location data when required for active trip operations or location-based service features.</li><li>Support, contact and service-safety records.</li></ul></section>
    <section><h2>2. Why Raahi uses it</h2><p>Raahi uses personal data to authenticate accounts, coordinate rides, enforce role and booking rules, verify Drivers, show relevant local supply, maintain FIFO and trip state, prevent abuse, investigate support issues and improve service reliability.</p></section>
    <section><h2>3. Contact sharing</h2><p>Raahi limits contact visibility to the service stage where it is needed. For Outstation, Driver and Passenger phone details become available after a quote is accepted. Verification documents such as Licence and RC scans are not shown to passengers; passengers receive verification status and approved vehicle information instead.</p></section>
    <section><h2>4. Location and trip information</h2><p>Location information is used only for service purposes such as selecting a current stand, live trip progress or matching local mobility demand. Raahi should not use individual trip/location data for unrelated advertising profiles.</p></section>
    <section><h2>5. Service providers and disclosures</h2><p>Raahi may use infrastructure, authentication, hosting, mapping, communications and similar service providers only as needed to operate the service. Data may also be disclosed where required by applicable law, to protect users, or to investigate fraud or safety incidents.</p></section>
    <section><h2>6. Retention and security</h2><p>Raahi keeps information for as long as reasonably needed for service operation, safety, dispute handling, legal obligations and audit history. Access to sensitive Driver verification documents is restricted. No online service can promise absolute security, so Raahi applies reasonable technical and operational safeguards and limits unnecessary access.</p></section>
    <section><h2>7. Your choices</h2><p>You may update your Raahi display name and verified phone through the service where available. For access, correction, deletion or other privacy requests, contact Raahi. Some records may need to be retained where required for legal, safety, fraud-prevention or audit purposes.</p></section>
    <section><h2>8. Children and inappropriate use</h2><p>Raahi is not designed for independent transactional use by a person who cannot legally consent to the service. A responsible adult should make and supervise travel arrangements where required.</p></section>
    <section><h2>9. Changes</h2><p>If this Policy materially changes, Raahi may require acknowledgement of a new version before further booking or Driver operations. The version and acceptance time are recorded against the account.</p></section>
  </LegalDocumentPage>;
}
