import Link from "next/link";
import { notFound } from "next/navigation";
import { TripOfferingActions } from "@/features/trips/TripOfferingActions";
import { formatTripDateTime } from "@/features/trips/format";
import { getTripOffering } from "@/server/projections/trips";

export default async function TripOfferingPage({params}:{params:Promise<{offeringId:string}>}){
 const {offeringId}=await params;const projection=await getTripOffering(offeringId);
 if(projection.status==="UNAUTHENTICATED")return <main className="min-h-screen bg-zinc-100 px-5 py-10"><div className="mx-auto max-w-xl rounded-3xl bg-white p-8 shadow-sm"><p className="text-sm font-medium text-zinc-500">Explore</p><h1 className="mt-2 text-3xl font-semibold">Sign in to view this Raahi Trip</h1><Link href={`/auth/sign-in?next=/explore/${offeringId}`} className="mt-6 inline-flex rounded-2xl bg-zinc-950 px-5 py-3 text-sm font-semibold text-white">Sign in</Link></div></main>;
 if(projection.status==="ERROR")throw new Error("TRIP_OFFERING_FAILED");
 if(projection.status==="NOT_FOUND"||!projection.offering)notFound();const t=projection.offering;
 return <main className="min-h-screen bg-zinc-100 px-5 py-10 text-zinc-950"><div className="mx-auto max-w-3xl"><Link href="/explore" className="text-sm font-semibold text-zinc-600">← Explore</Link><article className="mt-8 overflow-hidden rounded-3xl bg-white shadow-sm"><div className="flex min-h-48 items-end bg-zinc-950 p-7 text-white"><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-zinc-300">Raahi Trip · from {t.origin_name}</p><h1 className="mt-3 text-4xl font-semibold">{t.destination_name}</h1><p className="mt-2 text-sm text-zinc-300">Transport · destination wait · return</p></div></div>
 <div className="p-7"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className={`text-xs font-semibold uppercase tracking-[0.14em] ${t.display_status==="CONFIRMED"?"text-emerald-700":t.display_status==="FULL"?"text-zinc-500":"text-amber-700"}`}>{t.display_status}</p><p className="mt-3 text-lg font-semibold">Go · {formatTripDateTime(t.departure_at)}</p><p className="mt-1 text-lg font-semibold">Return · {formatTripDateTime(t.return_departure_at)}</p></div><div className="text-right"><p className="text-3xl font-semibold">₹{t.price_per_seat_inr}</p><p className="text-sm text-zinc-500">per seat · {t.seats_left} left</p></div></div>
 <section className="mt-6 rounded-2xl bg-emerald-50 p-5"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-emerald-800">Driver & vehicle trust</p><h2 className="mt-2 text-xl font-semibold">{t.driver_name}</h2><p className="mt-1 text-sm text-zinc-700">{t.vehicle_model} · {t.vehicle_registration}</p><div className="mt-3 flex flex-wrap gap-2 text-xs font-semibold text-emerald-800">{t.trust.driver_verified?<span className="rounded-full bg-white px-3 py-1">Driving licence verified</span>:null}{t.trust.driver_photo_verified?<span className="rounded-full bg-white px-3 py-1">Driver photo verified</span>:null}{t.trust.vehicle_rc_verified?<span className="rounded-full bg-white px-3 py-1">Vehicle RC verified</span>:null}{t.trust.vehicle_photos_verified?<span className="rounded-full bg-white px-3 py-1">Vehicle photos verified</span>:null}</div><p className="mt-3 text-xs leading-5 text-zinc-600">Raahi shows verification status, not private DL/RC documents.</p></section>
 {t.itinerary_context?<section className="mt-5 rounded-2xl border border-zinc-200 p-5"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-zinc-500">Driver’s plan</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-zinc-700">{t.itinerary_context}</p></section>:null}
 <section className="mt-5 rounded-2xl border border-zinc-200 p-5"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-zinc-500">What this Trip includes</p><p className="mt-2 text-sm leading-6 text-zinc-700">Raahi Trips initially cover shared transport, the destination wait and the return journey. Hotels, guides, meals, tickets and package-tour services are not bundled into this mobility promise.</p></section>
 {t.ride_status?<section className="mt-5 rounded-2xl border border-zinc-200 p-5"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-zinc-500">Trip state</p><p className="mt-2 font-semibold">{t.ride_status.replaceAll("_"," ").toLowerCase()}</p></section>:null}
 <TripOfferingActions offering={t}/></div></article></div></main>;
}
